services:
  - type: web
    name: resumatch
    env: docker
    region: ohio
    plan: starter
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///./data/resumatch.db
      - key: ALLOWED_ORIGINS
        value: https://resumatch-qd38.onrender.com
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
    healthCheckPath: /api/test
    numInstances: 1
    buildFilter:
      paths:
        - backend/**
        - frontend/**
        - requirements.txt
        - Dockerfile
        - docker-compose.yml 